export const RENDERER_RIGHT_MENU = {
	TOP: 'TOP',
	BOTTOM: 'BOTTOM',
	UP: 'UP',
	DOWN: 'DOWN',
	DELETE: 'DELETE',
	SELECTION: 'SELECTION',
	LOCK: 'LOCK',
	COPY: 'COPY',
	PASTE: 'PASTE'
} as const;

export type RendererRightMenuAction = typeof RENDERER_RIGHT_MENU[keyof typeof RENDERER_RIGHT_MENU];

export const RENDERER_RIGHT_MENU_ORDER: RendererRightMenuAction[] = [
	RENDERER_RIGHT_MENU.TOP,
	RENDERER_RIGHT_MENU.BOTTOM,
	RENDERER_RIGHT_MENU.UP,
	RENDERER_RIGHT_MENU.DOWN,
	RENDERER_RIGHT_MENU.DELETE,
	RENDERER_RIGHT_MENU.SELECTION,
	RENDERER_RIGHT_MENU.LOCK,
	RENDERER_RIGHT_MENU.COPY,
	RENDERER_RIGHT_MENU.PASTE
];
